[project]
name = "SUPPORT-cuda13"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = ["opencv-python>=4.11.0.86,<5"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
pip = "23.2.*"
python = "3.10.*"
numpy = "1.23.4.*"
tensorboard = "2.10.0.*"
tqdm = "4.64.1.*"
scikit-image = "0.19.2.*"
zarr = ">=2.18.2,<3"
pyright = ">=1.1.403,<2"
ruff = ">=0.14.6,<0.15"
ipykernel = ">=6.30.1,<7"
matplotlib = ">=3.9.4,<4"
pytorch-gpu = "*"
numba = ">=0.57.1,<0.58"
pyfftw = ">=0.15.0,<0.16"

[tool.pixi.pypi-dependencies]
pyqt5 = "==5.15.7"
pyqt5-qt5 = "==5.15.2"
pyqt5-sip = "==12.11.0"

[tool.pixi.tasks]

[tool.basedpyright]
venvPath = ".pixi/envs"
venv = "default"
typeCheckingMode = "standard"
reportMissingTypeStubs = false
